/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/S2LXgDF34zJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function ContactForm() {
  return (
    <Card className="w-full max-w-md mx-auto mt-16 border-none">
      <CardHeader>
        <CardTitle>Fale Conosco</CardTitle>
        <CardDescription>Precisa de um serviço customizado? Dúvidas em relação aos nossos serviços? Envie uma mensagem para nós!</CardDescription>
      </CardHeader>
      <CardContent>
        <form className="grid gap-4" action="https://api.web3forms.com/submit" method="POST">
        <Input type="hidden" name="access_key" value="3ce71964-55a9-41e7-8066-3300ead45259" />
        <Input type="hidden" name="from_name" value="Bike123" />
        <Input type="hidden" name="subject" value="Novo Contato Bike123" />
        <Input type="hidden" name="redirect" value="https://d2xhv7eva5h3do.cloudfront.net/contato/confirmacao/" />
          <div className="grid gap-2">
            <Label htmlFor="name">Nome<span className="text-red-600"> *</span></Label>
            <Input id="name" placeholder="Seu nome" name="nome" required />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="email">E-mail<span className="text-red-600"> *</span></Label>
            <Input id="email" type="email" placeholder="Seu e-mail" name="e-mail" required />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="phone">Telefone (opcional)</Label>
            <Input id="phone" type="tel" placeholder="Seu telefone (com DDD)" name="telefone" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="message">Mensagem<span className="text-red-600"> *</span></Label>
            <Textarea id="message" placeholder="Escreva sua mensagem" className="min-h-[120px]" name="mensagem" required />
          </div>
          <Input type="checkbox" name="botcheck" className="hidden"/>
          <Button type="submit" className="w-full bg-orange-400 hover:bg-orange-300 text-black">
            Enviar
          </Button>
        </form>
      </CardContent>
    </Card>
  )
}
