/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/I3pnMWBHdZN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Image from "next/image"

export function Featured() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Onde já aparecemos</h2>
          <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Veja o que estão falando sobre a gente
          </p>
        </div>
        <div className="grid w-full grid-cols-2 items-center justify-center gap-6 md:grid-cols-4 lg:gap-12">
          <Link href="https://bikeelegal.com/2017/05/09/so-para-mulheres-concorra-a-10-bolsas-em-mecanica-de-bicicleta/" rel="noopener noreferrer" target="_blank" className="mx-auto flex w-full items-center justify-center" prefetch={false}>
            <Image
              src="https://bike123-storage-d5766407193218-staging.s3.amazonaws.com/public/bike-e-legal.webp"
              width="140"
              height="70"
              alt="Logo Bike é Legal"
              className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
              unoptimized={true}
            />
          </Link>
          <Link href="https://catracalivre.com.br/educacao/bolsas-de-estudo-para-mulheres-em-curso-sobre-mecanica-de-bikes/" rel="noopener noreferrer" target="_blank" className="mx-auto flex w-full items-center justify-center" prefetch={false}>
            <Image
              src="https://bike123-storage-d5766407193218-staging.s3.amazonaws.com/public/brasil-cycle-fair.webp"
              width="140"
              height="70"
              alt="Logo Brasil Cycle Fair"
              className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
              unoptimized={true}
            />
          </Link>
          <Link href="https://catracalivre.com.br/educacao/bolsas-de-estudo-para-mulheres-em-curso-sobre-mecanica-de-bikes/" className="mx-auto flex w-full items-center justify-center" rel="noopener noreferrer" target="_blank" prefetch={false}>
            <Image
              src="https://bike123-storage-d5766407193218-staging.s3.amazonaws.com/public/catraca-livre.webp"
              width="140"
              height="70"
              alt="Logo Catraca Livre"
              className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
              unoptimized={true}
            />
          </Link>
          <Link href="https://economia.uol.com.br/empreendedorismo/noticias/redacao/2017/06/27/por-r-220-cursos-profissionais-para-oficinas-ensinam-a-manter-sua-bike.htm" className="mx-auto flex w-full items-center justify-center" rel="noopener noreferrer" target="_blank" prefetch={false}>
            <Image
              src="https://bike123-storage-d5766407193218-staging.s3.amazonaws.com/public/uol.webp"
              width="140"
              height="70"
              alt="Logo UOL"
              className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
              unoptimized={true}
            />
          </Link>
          <Link href="https://www.pedal.com.br/bike123-oferece-bolsas-integrais-em-cursos-profissionalizantes-para-mulheres_texto12019.html" className="mx-auto flex w-full items-center justify-center" rel="noopener noreferrer" target="_blank" prefetch={false}>
            <Image
              src="https://bike123-storage-d5766407193218-staging.s3.amazonaws.com/public/pedal-logo.webp"
              width="140"
              height="70"
              alt="Logo Pedal.com.br"
              className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
            />
          </Link>
          <Link href="http://transporteativo.org.br/ta/?p=9977" className="mx-auto flex w-full items-center justify-center" rel="noopener noreferrer" target="_blank" prefetch={false}>
            <Image
              src="https://bike123-storage-d5766407193218-staging.s3.amazonaws.com/public/transporte-ativo.webp"
              width="140"
              height="70"
              alt="Logo Transporte Ativo"
              className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
              unoptimized={true}
            />
          </Link>
          <Link href="https://www.youtube.com/watch?v=83WR8CXJjcc" className="mx-auto flex w-full items-center justify-center" rel="noopener noreferrer" target="_blank" prefetch={false}>
            <Image
              src="https://bike123-storage-d5766407193218-staging.s3.amazonaws.com/public/vamos-pedalar.webp"
              width="140"
              height="70"
              alt="Logo Vamos Pedalar"
              className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
              unoptimized={true}
            />
          </Link>
        </div>
      </div>
    </section>
  )
}
