/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/GjRoHFhJgfL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Footer() {
  return (
    <footer className="bg-[rgb(51,201,235)] text-black py-8">
      <div className="container mx-auto px-4 md:px-6 flex flex-col md:flex-row justify-between items-center">
        <div className="mb-4 md:mb-0">
          <h3 className="text-xl font-bold">Bike123</h3>
          <p className="text-sm font-light">Experts em serviços de manutenção em bicicletas.</p>
        </div>
        <div>
          <p className="text-sm font-light">&copy; 2024 Bike123. Todos os direitos reservados.</p>
          <p className="text-sm font-light">BIKE123 TECNOLOGIA LTDA 27.631.651/0001-36</p>
        </div>
        
      </div>
    </footer>
  )
}
