/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/EYQisatMMGw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function OpeningTitle() {
  return (
    <section className="w-full bg-[#33c9eb] py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6 text-center">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Sua bicicleta nas mãos de especialistas
          </h2>
          <p className="text md:text-xl">Economize tempo e pedale mais</p>
        </div>
      </div>
    </section>
  )
}
